### PR TITLE
DataPack fix for SM 1.10

### LINKED ISSUE #22: SM 1.10
Логика Датапаков изменилась в SM 1.10 (см. подробнее [здесь](https://github.com/alliedmodders/sourcemod/pull/688)).
Теперь любое записанное значение занимает ровно одну позицию, грубо говоря. Необходим "костыль-фикс".

### PR DESCRIPTION
**Pull request by CrazyHackGUT**
This resolves #22

### CODE REVIEW

**Comment by TiBarification** [comment]
I don't think that we need to merge it now, because there are no official news about releasing sourcemod 1.10 publicly. Also this change make shop core incompatible with current 1.8,1.9 versions of sourcemod.

**Comment by CrazyHackGUT** [comment]
This realization has compatibility with SM 1.8/1.9.
When plugin starts, he just creates DataPack, fills it "0", saves positions in global variables, and destroy DataPack.

Also SM 1.10 [can be downloaded](https://sm.alliedmods.net/smdrop/) right now.
It is likely that within six months, he will go in the "dev" branch, and stable will be replaced on 1.9.

**Comment by TiBarification** [comment]
@R1KO what you say about this?

**Comment by TiBarification** [comment]
@CrazyHackGUT please upload here smx file for testing.

**Comment by CrazyHackGUT** [comment]
[shop.smx.gz](https://github.com/R1KO/Shop-Core/files/1681605/shop.smx.gz)

**Comment by TonkiTon** [comment]
When the server starts, error - `[SM] Exception reported: Using item type other than none, ItemUseToggle callback must to be set
[SM] Blaming: shop.smx
[SM] Call stack trace:
[SM]   [0] ThrowNativeError
[SM]   [1] Line 601, shop/item_manager.sp::ItemManager_EndItem
[SM]   [3] Shop_EndItem
[SM]   [4] Line 127, shop_chat_1.0_CSGO_scp.sp::Shop_Started
[SM]   [6] Call_Finish
[SM]   [7] Line 273, shop/forwards.sp::Forward_NotifyShopLoaded
[SM]   [8] Line 396, shop.sp::OnReadyToStart
[SM]   [9] Line 532, shop/db.sp::DB_OnPlayersTableLoad
[SM] Exception reported: Using item type other than none, ItemUseToggle callback must to be set
[SM] Blaming: shop.smx
[SM] Call stack trace:
[SM]   [0] ThrowNativeError
[SM]   [1] Line 601, shop/item_manager.sp::ItemManager_EndItem
[SM]   [3] Shop_EndItem
[SM]   [4] Line 83, C:\Users\Dmitriy\Desktop\sourcemod-1.8.0-git5946-linux\addons\sourcemod\scripting\shop_pets_1.1.sp::Shop_Started
[SM]   [6] Call_Finish
[SM]   [7] Line 273, shop/forwards.sp::Forward_NotifyShopLoaded
[SM]   [8] Line 396, shop.sp::OnReadyToStart
[SM]   [9] Line 532, shop/db.sp::DB_OnPlayersTableLoad`

When you press on buy, error -`[SM] Exception reported: Data pack operation is out of bounds.
[SM] Blaming: shop.smx
[SM] Call stack trace:
[SM]   [0] DataPack.ReadCell
[SM]   [1] Line 1461, shop/item_manager.sp::ItemManager_FillCategories
[SM]   [2] Line 590, shop.sp::ShowCategories
[SM]   [3] Line 495, shop.sp::MainMenu_Handler
[SM] Exception reported: Data pack operation is out of bounds.
[SM] Blaming: shop.smx
[SM] Call stack trace:
[SM]   [0] DataPack.ReadCell
[SM]   [1] Line 1461, shop/item_manager.sp::ItemManager_FillCategories
[SM]   [2] Line 590, shop.sp::ShowCategories
[SM]   [3] Line 495, shop.sp::MainMenu_Handler
`

**Comment by CrazyHackGUT** [comment]
Try this: [shop.smx.gz](https://github.com/R1KO/Shop-Core/files/1685411/shop.smx.gz)

**Comment by TonkiTon** [comment]
Now works fine

**Pull request merged**
